name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configurando .Net 8...
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Instalando dependencias..
      run: dotnet restore
    - name: Compilando...
      run: dotnet build --configuration Release --no-restore
    - name: Ejecutando Tests...
      run: dotnet test --no-restore --verbosity normal
